/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package isad.ehu;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting(String izena) {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting(izena));
    }
}
