/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package isad.ehu;

public class App {
    public String getGreeting(String izena) {
        return ("Kaixo "+izena);
    }

    public static void main(String[] args) {
        if (args.length != 1) {
            System.out.println("Aplikazioak parametro bat behar du... (izen bat)");
        } else {
            System.out.println(new App().getGreeting(args[0]));
        }
    }
}
